---
- include: mysql.yml
- include: redis.yml
- include: memcached.yml
- include: database-setup.yml

- include: database-backup.yml
  when: db_backups_enabled

- include: elasticsearch.yml
  when: elasticsearch_enabled
