---
- name: install mysql
  yum:
    name: "{{ item }}"
    enablerepo: remi,epel
    state: present
  with_items:
    - mariadb-server
    - mariadb
    - MySQL-python
  tags: mysql

- name: mysql | install mysql-python
  easy_install:
    name: mysql-python
  tags: mysql

- name: mysql | start service
  service:
    name: mariadb
    state: started
    enabled: yes
  tags: mysql

# http://stackoverflow.com/a/16652653/605707
- name: mysql | change root user pass
  mysql_user:
    login_user: root
    login_password: ''
    name: root
    password: ''
    priv: "*.*:ALL,GRANT"
    host: "{{ item }}"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  ignore_errors: true
  tags: mysql

- name: mysql | import timezone info
  shell: mysql_tzinfo_to_sql /usr/share/zoneinfo > /opt/tzinfo.sql && cat /opt/tzinfo.sql | mysql mysql
  args:
    creates: /opt/tzinfo.sql
  tags: mysql

#- name: mysql | copy .my.cnf file with root password credentials
#  template:
#    src: my.cnf.j2
#    dest: /root/.my.cnf
#    owner: root
#    mode: 0600
#  tags: mysql
#
#- name: mysql | delete anonymous user server hostname
#  mysql_user:
#    user: ""
#    host: "{{ ansible_fqdn }}"
#    state: absent
#  tags: mysql
#
#- name: mysql delete anonymous user for localhost
#  mysql_user:
#    user: ""
#    state: absent
#  tags: mysql
#
#- name: mysql | remove test database
#  mysql_db:
#    name: test
#    state: absent
#  tags: mysql
