---
- name: firewall | disable firewalld
  service:
    name: firewalld
    enabled: no
    state: stopped
  tags: firewall

- name: firewall | install yum packages
  yum:
    name: "{{ item }}"
    enablerepo: epel
    state: present
  with_items:
    - iptables-services
    - fail2ban
  tags: firewall

- name: firewall | start fail2ban service
  service:
    name: fail2ban
    state: started
    enabled: yes
  tags: firewall

- name: firewall | copy jail.local config
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
  notify: restart fail2ban
  tags: firewall

- name: firewall | disable firewalld
  service:
    name: firewalld
    enabled: no
    state: stopped
  tags: firewall

- name: firewall | mask firewalld
  command: systemctl mask firewalld
  ignore_errors: True

- name: firewall | enable iptables
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - iptables
    - ip6tables
  tags: firewall

- name: firewall | install iptables firewall
  template:
    src: iptables.j2
    dest: /etc/sysconfig/iptables
    owner: root
    group: root
    mode: 0600
  notify: restart iptables
  tags: firewall
