---
- name: yum | install remi repo
  yum:
    name: "http://rpms.famillecollet.com/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
    state: present
  tags: yum

- name: yum | install remi GPG key
  rpm_key:
    key: "http://rpms.remirepo.net/RPM-GPG-KEY-remi"
    state: present
  tags: yum

- name: yum | install epel repo
  yum:
    name: "http://download.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  tags: yum

- name: yum | install epel GPG key
  rpm_key:
    key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    state: present
  tags: yum

- name: yum | install Development Tools group
  yum:
    name: "@Development tools"
    state: present
  tags: yum

- name: yum | install system dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - bzip2
    - curl-devel
    - sqlite-devel
    - libyaml-devel
    - libxml2-devel
    - mariadb-devel
    - uuid
