---
- name: application | create the web group
  group:
    name: "{{ web_group }}"
    state: present
  tags: application

- name: application | create web user
  user:
    name: "{{ web_user }}"
    state: present
    createhome: yes
    groups: "{{ web_group }}"
  tags: application

- name: sites | add public key to web user
  authorized_key:
    user: "{{ web_user }}"
    state: present
    manage_dir: yes
    key: "{{ lookup('file', web_key) }}"
  tags: sites

- include: apache.yml
- include: sites.yml
- include: php.yml
